---

# Copyright 2019 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- hosts: san_eng_zone_seed_san_a
  gather_facts: False

  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: "{{fos_user_name}}"
      fos_password: "{{fos_password}}"
      https: "{{fos_https}}"

  tasks:

  - name: gather facts
    brocade_facts:
      credential: "{{credential}}"
      vfid: -1
      gather_subset:
        - brocade_zoning
        - brocade_security_ipfilter_policy

  - name: gather facts for brocade_chassis_chassis
    brocade_singleton_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_chassis"
      obj_name: "chassis"

  - name: gather facts for brocade_fibrechannel_configuration_fabric
    brocade_singleton_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_fibrechannel_configuration"
      obj_name: "fabric"

  - name: gather facts for brocade_fibrechannel_configuration_port_configuration
    brocade_singleton_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_fibrechannel_configuration"
      obj_name: "port_configuration"

  - name: gather facts for brocade_fibrechannel_switch_fibrechannel_switch
    brocade_list_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_fibrechannel_switch"
      list_name: "fibrechannel_switch"

  - name: gather facts for brocade_interface_fibrechannel
    brocade_list_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_interface"
      list_name: "fibrechannel"

  - name: gather facts for brocade_logging_audit
    brocade_singleton_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_logging"
      obj_name: "audit"

  - name: gather facts for brocade_logging_syslog_server
    brocade_list_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_logging"
      list_name: "syslog_server"

  - name: gather facts for brocade_snmp_system
    brocade_singleton_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_snmp"
      obj_name: "system"

  - name: gather facts for brocade_time_clock_server
    brocade_singleton_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_time"
      obj_name: "clock_server"

  - name: gather facts for brocade_time_time_zone
    brocade_singleton_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_time"
      obj_name: "time_zone"

  - name: gather facts for brocade_security_user_config
    brocade_list_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_security"
      list_name: "user_config"

  - name: gather facts for brocade_security_ipfilter_rule
    brocade_list_obj_facts:
      credential: "{{credential}}"
      vfid: -1
      module_name: "brocade_security"
      list_name: "ipfilter_rule"

  - name: print ansible_facts gathered
    debug:
      var: ansible_facts
